#############################################################################
# Makefile for building: animatedWeather
# Generated by qmake (3.1) (Qt 5.15.5)
# Project:  animatedWeather.pro
# Template: app
# Command: /opt/qt5pi/hostBinaries/bin/qmake -o Makefile animatedWeather.pro -spec devices/linux-rasp-pi3-brcm-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
CXX           = /opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt5pi/targetBinaries/include -I/opt/qt5pi/targetBinaries/include/QtWebEngine -I/opt/qt5pi/targetBinaries/include/QtWebEngineCore -I/opt/qt5pi/targetBinaries/include/QtQuick -I/opt/qt5pi/targetBinaries/include/QtGui -I/opt/qt5pi/targetBinaries/include/QtQmlModels -I/opt/qt5pi/targetBinaries/include/QtWebChannel -I/opt/qt5pi/targetBinaries/include/QtQml -I/opt/qt5pi/targetBinaries/include/QtNetwork -I/opt/qt5pi/targetBinaries/include/QtPositioning -I/opt/qt5pi/targetBinaries/include/QtCore -I. -I/opt/qt5pi/sysroot/opt/vc/include -I/opt/qt5pi/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qt5pi/sysroot/opt/vc/include/interface/vmcs_host/linux -I/opt/qt5pi/hostBinaries/mkspecs/devices/linux-rasp-pi3-brcm-g++
QMAKE         = /opt/qt5pi/hostBinaries/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5pi/hostBinaries/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5pi/hostBinaries/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = animatedWeather1.0.0
DISTDIR = /home/milad/animated-Weather/.tmp/animatedWeather1.0.0
LINK          = /opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/opt/qt5pi/targetBinaries/lib -Wl,-rpath-link,/opt/qt5pi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/qt5pi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/opt/qt5pi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/opt/qt5pi/sysroot/opt/vc/lib /opt/qt5pi/targetBinaries/lib/libQt5WebEngine.so /opt/qt5pi/targetBinaries/lib/libQt5WebEngineCore.so /opt/qt5pi/targetBinaries/lib/libQt5Quick.so /opt/qt5pi/targetBinaries/lib/libQt5Gui.so /opt/qt5pi/targetBinaries/lib/libQt5QmlModels.so /opt/qt5pi/targetBinaries/lib/libQt5WebChannel.so /opt/qt5pi/targetBinaries/lib/libQt5Qml.so /opt/qt5pi/targetBinaries/lib/libQt5Network.so /opt/qt5pi/targetBinaries/lib/libQt5Positioning.so /opt/qt5pi/targetBinaries/lib/libQt5Core.so -lbrcmGLESv2 -lbcm_host -lvcos -lvchiq_arm -pthread -lpthread   
AR            = /opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = /opt/qt5pi/hostBinaries/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/hostBinaries/mkspecs/common/unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/linux.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/sanitize.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/g++-base.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/qdevice.pri \
		/opt/qt5pi/hostBinaries/mkspecs/features/device_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/hostBinaries/mkspecs/qconfig.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/linux-rasp-pi3-brcm-g++/qmake.conf \
		/opt/qt5pi/hostBinaries/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/hostBinaries/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/toolchain.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/default_pre.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/default_post.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qml_debug.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/warn_on.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resources_functions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resources.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/moc.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/file_copies.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/exceptions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/yacc.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/lex.prf \
		animatedWeather.pro  main.cpp
QMAKE_TARGET  = animatedWeather
DESTDIR       = 
TARGET        = animatedWeather


first: all
####### Build rules

animatedWeather:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: animatedWeather.pro /opt/qt5pi/hostBinaries/mkspecs/devices/linux-rasp-pi3-brcm-g++/qmake.conf /opt/qt5pi/hostBinaries/mkspecs/features/spec_pre.prf \
		/opt/qt5pi/hostBinaries/mkspecs/common/unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/linux.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/sanitize.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/g++-base.conf \
		/opt/qt5pi/hostBinaries/mkspecs/common/g++-unix.conf \
		/opt/qt5pi/hostBinaries/mkspecs/qdevice.pri \
		/opt/qt5pi/hostBinaries/mkspecs/features/device_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_post.conf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qt5pi/hostBinaries/mkspecs/qconfig.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt_functions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/devices/linux-rasp-pi3-brcm-g++/qmake.conf \
		/opt/qt5pi/hostBinaries/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5pi/hostBinaries/mkspecs/features/exclusive_builds.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/toolchain.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/default_pre.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resolve_config.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/default_post.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qml_debug.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/warn_on.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qt.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resources_functions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/resources.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/moc.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/unix/opengl.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/unix/thread.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/qmake_use.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/file_copies.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/testcase_targets.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/exceptions.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/yacc.prf \
		/opt/qt5pi/hostBinaries/mkspecs/features/lex.prf \
		animatedWeather.pro \
		qml.qrc
	$(QMAKE) -o Makefile animatedWeather.pro -spec devices/linux-rasp-pi3-brcm-g++ CONFIG+=debug CONFIG+=qml_debug
/opt/qt5pi/hostBinaries/mkspecs/features/spec_pre.prf:
/opt/qt5pi/hostBinaries/mkspecs/common/unix.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/linux.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/sanitize.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/gcc-base-unix.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/g++-base.conf:
/opt/qt5pi/hostBinaries/mkspecs/common/g++-unix.conf:
/opt/qt5pi/hostBinaries/mkspecs/qdevice.pri:
/opt/qt5pi/hostBinaries/mkspecs/features/device_config.prf:
/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_pre.conf:
/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_device_post.conf:
/opt/qt5pi/hostBinaries/mkspecs/devices/common/linux_arm_device_post.conf:
/opt/qt5pi/hostBinaries/mkspecs/qconfig.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_contacts_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_feedback_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_organizer_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versit_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_versitorganizer_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qt5pi/hostBinaries/mkspecs/features/qt_functions.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/qt_config.prf:
/opt/qt5pi/hostBinaries/mkspecs/devices/linux-rasp-pi3-brcm-g++/qmake.conf:
/opt/qt5pi/hostBinaries/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5pi/hostBinaries/mkspecs/features/exclusive_builds.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/toolchain.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/default_pre.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/resolve_config.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/default_post.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/qml_debug.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/warn_on.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/qt.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/resources_functions.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/resources.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/moc.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/unix/opengl.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/unix/thread.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/qmake_use.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/file_copies.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/testcase_targets.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/exceptions.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/yacc.prf:
/opt/qt5pi/hostBinaries/mkspecs/features/lex.prf:
animatedWeather.pro:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile animatedWeather.pro -spec devices/linux-rasp-pi3-brcm-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile animatedWeather

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5pi/hostBinaries/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/opt/qt5pi/hostBinaries/bin/rcc \
		main.qml \
		wtools/index.html \
		wtools/css/font.css \
		wtools/css/weather-icons.min.css \
		wtools/css/style.css \
		wtools/fonts/weathericons-regular-webfont.woff \
		wtools/fonts/S6u9w4BMUTPHh7USSwiPHA.ttf \
		wtools/fonts/weathericons-regular-webfont.woff2 \
		wtools/fonts/MAINFONT.TTF \
		wtools/fonts/weathericons-regular-webfont.ttf \
		wtools/js/snap.svg-min.js \
		wtools/js/TweenMax.min.js \
		wtools/js/persionCalander.js \
		wtools/js/conditions.js \
		wtools/js/script.js \
		wtools/js/jquery-2.2.4.min.js
	/opt/qt5pi/hostBinaries/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5pi/hostBinaries/mkspecs/features/data/dummy.cpp
	/opt/raspiToolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/opt/qt5pi/sysroot -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /opt/qt5pi/hostBinaries/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp /opt/qt5pi/targetBinaries/include/QtGui/QGuiApplication \
		/opt/qt5pi/targetBinaries/include/QtGui/qguiapplication.h \
		/opt/qt5pi/targetBinaries/include/QtGui/qtguiglobal.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qglobal.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qconfig.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qtcore-config.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qsystemdetection.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qprocessordetection.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcompilerdetection.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qtypeinfo.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qsysinfo.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qlogging.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qflags.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qatomic.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qbasicatomic.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qgenericatomic.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qatomic_cxx11.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qatomic_msvc.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qglobalstatic.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qmutex.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qnumeric.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qversiontagging.h \
		/opt/qt5pi/targetBinaries/include/QtGui/qtgui-config.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcoreapplication.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstring.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qchar.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qbytearray.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qrefcount.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qnamespace.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qarraydata.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringliteral.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringalgorithms.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringview.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringbuilder.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qobject.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qobjectdefs.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qlist.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qalgorithms.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qiterator.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qhashfunctions.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qpair.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qvector.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcontainertools_impl.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qpoint.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qbytearraylist.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringlist.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qregexp.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qstringmatcher.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcoreevent.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qscopedpointer.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qmetatype.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qvarlengtharray.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcontainerfwd.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qobject_impl.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qeventloop.h \
		/opt/qt5pi/targetBinaries/include/QtGui/qwindowdefs.h \
		/opt/qt5pi/targetBinaries/include/QtGui/qwindowdefs_win.h \
		/opt/qt5pi/targetBinaries/include/QtGui/qinputmethod.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qlocale.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qvariant.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qmap.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qdebug.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qhash.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qtextstream.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qiodevice.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qset.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qcontiguouscache.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qsharedpointer.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qshareddata.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qsize.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qmargins.h \
		/opt/qt5pi/targetBinaries/include/QtQml/QQmlApplicationEngine \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlapplicationengine.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlengine.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qurl.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qurlquery.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qjsengine.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qjsvalue.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qtqmlglobal.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qtqml-config.h \
		/opt/qt5pi/targetBinaries/include/QtNetwork/qtnetworkglobal.h \
		/opt/qt5pi/targetBinaries/include/QtNetwork/qtnetwork-config.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmldebug.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqml.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlprivate.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlparserstatus.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmllist.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qpointer.h \
		/opt/qt5pi/targetBinaries/include/QtCore/qmetaobject.h \
		/opt/qt5pi/targetBinaries/include/QtQml/qqmlerror.h \
		/opt/qt5pi/targetBinaries/include/QtWebEngine/qtwebengineglobal.h \
		/opt/qt5pi/targetBinaries/include/QtWebEngine/qtwebengine-config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/animatedWeather/bin || mkdir -p $(INSTALL_ROOT)/opt/animatedWeather/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/animatedWeather/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/animatedWeather/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/animatedWeather/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

